### ISSUE TITLE
build an automated exercise solver

### ISSUE THREAD

**Issue by tiagoarodrigues55** [MatthiasSaihttam/ka-hearth#3]
Hi Matthias, 
I saw that you’re following updates to the khan academy, and I’m looking for ways to create an automated way to resolve my recommendations. Can you help me? Thank you and congratulations for the work!

**Comment by MatthiasPortzel** [comment]
I don't really understand what you're asking for or hoping to accomplish. I may be able to help if you have a specific technical question, but I honestly don't use the exercise section of the website at all.

**Comment by tiagoarodrigues55** [comment]
I'm looking for some way to create a script that can make the recommendations of the khan academy, the idea is to create a script that can interact with the khan api so that it can receive the recommendations of a specific user and can send an answer for each exercise. The point is that my teacher sends me a lot of recommendations every week so I would like to create a script to make them for me. I searched a lot on Github and your repository was one of the ones that came closest to being able to help me ...

**Comment by MatthiasPortzel** [comment]
So you're looking for a script that will do your homework for you. I'm not particularly motivated to help you there.

I'm not familiar with the recommendations system, but theoretically you could grab those. The hard part is that the script has to know the right answer to the problem. You would have to write a program to solve every type of math problem KA could throw at you (there are only [around 1,500](https://khanacademy.fandom.com/wiki/Category:Math_exercises)).

There's nothing that I know of that already does this. Nothing is impossible, but suffice it to say, you would spend significantly more time building this than you would just doing the recommendations.
